/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prolab;

public class home extends javax.swing.JFrame {

    public home() {
        initComponents();
        setExtendedState(library.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newbook = new javax.swing.JButton();
        removebook = new javax.swing.JButton();
        borrowbook = new javax.swing.JButton();
        returnbook = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newbook.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC LAND\\Desktop\\Icon 1\\Icon 1\\New book.png")); // NOI18N
        newbook.setText("Add a new book");
        newbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbookActionPerformed(evt);
            }
        });
        getContentPane().add(newbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 41, -1, -1));

        removebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removebook.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC LAND\\Desktop\\Icon 1\\Icon 1\\red-x-mark-transparent-background-3.png")); // NOI18N
        removebook.setText("Remove book");
        removebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebookActionPerformed(evt);
            }
        });
        getContentPane().add(removebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 41, 163, 57));

        borrowbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrowbook.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC LAND\\Desktop\\Icon 1\\Icon 1\\return book png.png")); // NOI18N
        borrowbook.setText("Borrow  book");
        borrowbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbookActionPerformed(evt);
            }
        });
        getContentPane().add(borrowbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 161, 196, 50));

        returnbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnbook.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC LAND\\Desktop\\Icon 1\\Icon 1\\return-book-1-560407.png")); // NOI18N
        returnbook.setText("return book");
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        getContentPane().add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 157, -1, -1));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC LAND\\Desktop\\Icon 1\\Icon 1\\exit.png")); // NOI18N
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 248, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbookActionPerformed
new newbook().setVisible(true ); 

    }//GEN-LAST:event_newbookActionPerformed

    private void removebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebookActionPerformed
        new removebook().setVisible(true ); 
    }//GEN-LAST:event_removebookActionPerformed

    private void borrowbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbookActionPerformed
       new borrowbook().setVisible(true ); 
    }//GEN-LAST:event_borrowbookActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new library().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
        new returnbook().setVisible(true ); 
    }//GEN-LAST:event_returnbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowbook;
    private javax.swing.JButton logout;
    private javax.swing.JButton newbook;
    private javax.swing.JButton removebook;
    private javax.swing.JButton returnbook;
    // End of variables declaration//GEN-END:variables
}
